name: 'Test service-jehlomat'

on:
  pull_request:
    paths:
      - 'service-jehlomat/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: huaxk/postgis-action@v1
        with:
          postgresql password: 'password'
          postgresql user: 'jehlomat'
          postgresql db: 'jehlomat'
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'
      - name: 'Run unit tests'
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USERNAME: jehlomat
          PGPASSWORD: password
          DATABASE_NAME: jehlomat
        run: |
          psql -h localhost -p 5432 -U jehlomat -d jehlomat -f ./service-jehlomat/src/main/resources/postgis.sql
          psql -h localhost -p 5432 -U jehlomat -d jehlomat -f ./service-jehlomat/src/test/resources/obce.sql
          psql -h localhost -p 5432 -U jehlomat -d jehlomat -f ./service-jehlomat/src/test/resources/mc.sql
          psql -h localhost -p 5432 -U jehlomat -d jehlomat -f ./service-jehlomat/src/test/resources/okres.sql
          psql -h localhost -p 5432 -U jehlomat -d jehlomat -f ./service-jehlomat/src/main/resources/create_table.sql
          ./gradlew service-jehlomat:test --no-daemon --stacktrace
